/**
 * Turns schema.ts's declaration into collections, fields and relations on a
 * live Directus. This is what makes "schema as code" true rather than
 * aspirational — the alternative is a human clicking collections into
 * existence, which leaves the estate's shape known only to the running
 * instance: no review, no diff, no rebuild after a bad migration.
 *
 * THE ONLY WRITER IN src/directus, AND IT IS NOT A REQUEST PATH. Nothing
 * mounts this on a route, and nothing calls it at provision. It is invoked by
 * `scripts/directus-schema.ts`, by hand, by an operator holding an ADMIN
 * token — a different, higher-privilege credential than the read-only
 * DIRECTUS_TOKEN the Worker carries (see src/env.ts). The Worker must never
 * be able to alter the estate's structure; a bug in a request handler should
 * not be able to drop a column.
 *
 * IDEMPOTENT BY CONSTRUCTION. Every step probes before it writes, so a
 * re-run after adding one field creates exactly that field. It never DELETES
 * and never ALTERS: a field whose declaration changed is reported, not
 * rewritten. Directus type changes can silently discard data, and a script
 * that quietly does that to a contract row is not a script anyone should run
 * twice. The operator gets a list and makes the call.
 *
 * Lives in src/ rather than in the script itself so `bun run check` type
 * checks it and `bun run test` exercises the payloads against a mocked fetch.
 * scripts/ is outside every tsconfig project here (see scripts/build-page.ts,
 * the existing precedent), so logic that lives only there is logic nothing
 * verifies.
 */

import { ESTATE_SCHEMA, type CollectionDef, type FieldDef } from "./schema";

export interface AdminConfig {
  /** Instance origin, no trailing slash. */
  url: string;
  /** ADMIN token — not the Worker's read-only DIRECTUS_TOKEN. */
  token: string;
}

/** The subset of `fetch` this module uses, injectable so tests need no
 *  network and no global patching. */
export type FetchLike = (url: string, init: RequestInit) => Promise<Response>;

export interface ApplyReport {
  collectionsCreated: string[];
  collectionsExisting: string[];
  fieldsCreated: string[];
  fieldsExisting: string[];
  relationsCreated: string[];
  relationsExisting: string[];
  /** Declared differently here than on the instance. Reported, never
   *  rewritten — see this file's header. */
  mismatched: string[];
}

/**
 * The primary key every collection gets: a uuid, generated by Directus.
 *
 * A uuid rather than an auto-increment integer because these rows are
 * referenced from outside Directus (an issue body, a checklist, a client
 * portal URL), and a guessable sequential id on a client-facing surface
 * invites enumeration. The HUMAN-facing handles are `estate_projects.key`
 * and `estate_requirements.ref`, which is the pairing the whole schema is
 * built around: a stable readable handle for people, an opaque id for
 * relations.
 */
export function primaryKeyField(): Record<string, unknown> {
  return {
    field: "id",
    type: "uuid",
    meta: { hidden: true, readonly: true, interface: "input", special: ["uuid"] },
    schema: { is_primary_key: true, length: 36, has_auto_increment: false },
  };
}

/** POST /collections body. */
export function collectionPayload(def: CollectionDef): Record<string, unknown> {
  return {
    collection: def.collection,
    meta: { note: def.note, icon: "database", singleton: false },
    schema: { name: def.collection },
    fields: [primaryKeyField()],
  };
}

/**
 * POST /fields/:collection body.
 *
 * `choices` becomes a select-dropdown rather than a database CHECK
 * constraint, deliberately: Directus renders the dropdown (so a human editing
 * from a phone cannot typo a status), while a CHECK would make adding a state
 * later a migration. The enforcement that matters is in the Worker —
 * portal.ts's `clientStatus` publishes nothing for a state it does not
 * recognise, so an unexpected value fails safe rather than reaching a client.
 */
export function fieldPayload(def: FieldDef): Record<string, unknown> {
  const meta: Record<string, unknown> = {
    note: def.note,
    required: def.nullable === false,
    interface: def.choices ? "select-dropdown" : undefined,
    options: def.choices
      ? { choices: def.choices.map((value) => ({ text: value, value })) }
      : undefined,
  };
  return {
    field: def.field,
    type: def.type,
    meta,
    schema: {
      is_nullable: def.nullable !== false,
      is_unique: def.unique === true,
    },
  };
}

/**
 * POST /relations body for an m2o.
 *
 * `on_delete: "SET NULL"` throughout, never CASCADE. Deleting a project must
 * not silently delete its contract, its requirements and its decision log —
 * the estate outlives the engagement (schema.ts's own `archived` status
 * exists for exactly that), and orphaned rows an operator can see beat rows
 * that vanished. The self-relation on `estate_decisions.supersedes` needs it
 * too: a superseding decision being deleted must not take the history with
 * it.
 */
export function relationPayload(collection: string, def: FieldDef): Record<string, unknown> {
  return {
    collection,
    field: def.field,
    related_collection: def.relatedCollection,
    meta: { sort_field: null },
    schema: { on_delete: "SET NULL" },
  };
}

async function adminRequest(
  fetchLike: FetchLike, cfg: AdminConfig, method: string, path: string, body?: unknown,
): Promise<Response> {
  return fetchLike(`${cfg.url}${path}`, {
    method,
    headers: {
      authorization: `Bearer ${cfg.token}`,
      accept: "application/json",
      ...(body === undefined ? {} : { "content-type": "application/json" }),
    },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
  });
}

/**
 * Reads one object, or `null` when it is not there.
 *
 * Directus answers 403 (not 404) for something the token cannot see, which
 * for an ADMIN token means it does not exist. Both count as absent; anything
 * else is a real failure and propagates rather than being read as "missing",
 * because a transient 500 read as missing would make the next step try to
 * CREATE a collection that already holds data.
 */
async function readObject(
  fetchLike: FetchLike, cfg: AdminConfig, path: string,
): Promise<Record<string, unknown> | null> {
  const res = await adminRequest(fetchLike, cfg, "GET", path);
  if (res.status === 403 || res.status === 404) return null;
  if (!res.ok) {
    throw new Error(`directus admin GET ${path} failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  }
  const body = await res.json() as { data?: Record<string, unknown> };
  return body.data ?? {};
}

/**
 * Compares a live field against its declaration on the three things that
 * would silently change meaning: its type, whether it is nullable, and
 * whether it is unique.
 *
 * Returns a human-readable difference, or null. NOT a fixer — see this file's
 * header on why nothing is altered: a Directus type change can discard the
 * column's data, and doing that unattended to a contract row is not a thing a
 * re-runnable script should be able to do.
 */
export function fieldMismatch(
  def: FieldDef, live: Record<string, unknown>,
): string | null {
  const schema = (live.schema ?? {}) as Record<string, unknown>;
  const diffs: string[] = [];
  if (typeof live.type === "string" && live.type !== def.type) {
    diffs.push(`type ${live.type} != declared ${def.type}`);
  }
  const declaredNullable = def.nullable !== false;
  if (typeof schema.is_nullable === "boolean" && schema.is_nullable !== declaredNullable) {
    diffs.push(`is_nullable ${schema.is_nullable} != declared ${declaredNullable}`);
  }
  const declaredUnique = def.unique === true;
  if (typeof schema.is_unique === "boolean" && schema.is_unique !== declaredUnique) {
    diffs.push(`is_unique ${schema.is_unique} != declared ${declaredUnique}`);
  }
  return diffs.length === 0 ? null : diffs.join("; ");
}

async function create(
  fetchLike: FetchLike, cfg: AdminConfig, path: string, body: unknown, what: string,
): Promise<void> {
  const res = await adminRequest(fetchLike, cfg, "POST", path, body);
  if (!res.ok) {
    throw new Error(`directus admin create ${what} failed (${res.status}): ${(await res.text()).slice(0, 300)}`);
  }
}

/**
 * Applies the whole declaration, in ESTATE_SCHEMA's own order (projects
 * first — see that constant's doc comment: Directus rejects a relation to a
 * collection that does not exist yet).
 *
 * Per collection: create it if absent, then walk its fields creating what is
 * missing, then create the relation for any m2o field. Relations are created
 * AFTER all collections exist, in a second pass, because a self-relation
 * (`estate_decisions.supersedes`) and any forward reference would otherwise
 * depend on declaration order twice over.
 *
 * A field that exists but was declared differently lands in
 * `report.mismatched`. Nothing is altered — see the header.
 */
export async function applyEstateSchema(
  cfg: AdminConfig, fetchLike: FetchLike, schema: readonly CollectionDef[] = ESTATE_SCHEMA,
): Promise<ApplyReport> {
  const report: ApplyReport = {
    collectionsCreated: [], collectionsExisting: [], fieldsCreated: [], fieldsExisting: [],
    relationsCreated: [], relationsExisting: [], mismatched: [],
  };

  for (const def of schema) {
    if (await readObject(fetchLike, cfg, `/collections/${def.collection}`) !== null) {
      report.collectionsExisting.push(def.collection);
    } else {
      await create(fetchLike, cfg, "/collections", collectionPayload(def), def.collection);
      report.collectionsCreated.push(def.collection);
    }

    for (const field of def.fields) {
      const label = `${def.collection}.${field.field}`;
      const live = await readObject(fetchLike, cfg, `/fields/${def.collection}/${field.field}`);
      if (live !== null) {
        report.fieldsExisting.push(label);
        const diff = fieldMismatch(field, live);
        if (diff !== null) report.mismatched.push(`${label}: ${diff}`);
        continue;
      }
      await create(fetchLike, cfg, `/fields/${def.collection}`, fieldPayload(field), label);
      report.fieldsCreated.push(label);
    }
  }

  // Second pass: every collection now exists, so a relation can point
  // anywhere the declaration names — including forward and at itself.
  for (const def of schema) {
    for (const field of def.fields) {
      if (field.relatedCollection === undefined) continue;
      const label = `${def.collection}.${field.field} -> ${field.relatedCollection}`;
      if (await readObject(fetchLike, cfg, `/relations/${def.collection}/${field.field}`) !== null) {
        report.relationsExisting.push(label);
        continue;
      }
      await create(fetchLike, cfg, "/relations", relationPayload(def.collection, field), label);
      report.relationsCreated.push(label);
    }
  }

  return report;
}
